### ISSUE TITLE
Normal software license

### ISSUE THREAD

**Issue by aehlke** [mlbonniec/OnBoardingKit#10]
Please use a license like MIT or BSD - you can find ones of these that also require attribution. CC isn't well established for software and many orgs cannot use

**Comment by mlbonniec** [comment]
Hi, thanks for your request. 
I did some research, and it appears that you're right. CC is not very recommended for open-source codes.
I'm changing the license to MIT.

**Comment by aehlke** [comment]
If attribution is important to you then I recommend having a disclaimer reminding people about MIT's attribution requirements, because they're sometimes skipped over more often than CC-BY-SA imo

**Comment by mlbonniec** [comment]
Yes, you're right. I'll add a note to remind people who use the library about the attribution.

Are you planning to use it yourself ?

**Comment by aehlke** [comment]
Sorry I evaluated it and considered it but ended up building my own with the iOS 17 APIs that have made it pretty easy these days

**Comment by mlbonniec** [comment]
No problem :\)

Thanks anyway for your license advise!

**Comment by aehlke** [comment]
Sorry to take your time, I asked about the license when I was still figuring out what to use or fork

My WIP is here https://github.com/lake-of-fire/LakeKit/blob/main/Sources/LakeKit/OnboardingSheet.swift but it does not yet have an open src license. I aim to open it later on with an accompanying app to manage/deploy templated apps + web stacks.

Mine combines onboarding with a paywall (free mode + upsells for paid), plus macOS
